version: "3.8"

services:
  app:
    build: .
    container_name: sistema-escola-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker
    depends_on:
      - mysql
    command: npm run dev # ✅ Corrigido aqui

  mysql:
    image: mysql:8.0
    container_name: sistema-escola-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: sistema_escola
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema-escola-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: senha123

volumes:
  db_data:
